// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: pkg/infrastructure/pb/auth_client.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestUserId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *RequestUserId) Reset() {
	*x = RequestUserId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_infrastructure_pb_auth_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestUserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUserId) ProtoMessage() {}

func (x *RequestUserId) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infrastructure_pb_auth_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUserId.ProtoReflect.Descriptor instead.
func (*RequestUserId) Descriptor() ([]byte, []int) {
	return file_pkg_infrastructure_pb_auth_client_proto_rawDescGZIP(), []int{0}
}

func (x *RequestUserId) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ResponseBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExistStatus  bool   `protobuf:"varint,1,opt,name=ExistStatus,proto3" json:"ExistStatus,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
}

func (x *ResponseBool) Reset() {
	*x = ResponseBool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_infrastructure_pb_auth_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBool) ProtoMessage() {}

func (x *ResponseBool) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infrastructure_pb_auth_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBool.ProtoReflect.Descriptor instead.
func (*ResponseBool) Descriptor() ([]byte, []int) {
	return file_pkg_infrastructure_pb_auth_client_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseBool) GetExistStatus() bool {
	if x != nil {
		return x.ExistStatus
	}
	return false
}

func (x *ResponseBool) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ResponseUserDetailsLite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMessage      string `protobuf:"bytes,1,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	UserName          string `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	UserProfileImgURL string `protobuf:"bytes,3,opt,name=UserProfileImgURL,proto3" json:"UserProfileImgURL,omitempty"`
}

func (x *ResponseUserDetailsLite) Reset() {
	*x = ResponseUserDetailsLite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_infrastructure_pb_auth_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseUserDetailsLite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUserDetailsLite) ProtoMessage() {}

func (x *ResponseUserDetailsLite) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infrastructure_pb_auth_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUserDetailsLite.ProtoReflect.Descriptor instead.
func (*ResponseUserDetailsLite) Descriptor() ([]byte, []int) {
	return file_pkg_infrastructure_pb_auth_client_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseUserDetailsLite) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ResponseUserDetailsLite) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ResponseUserDetailsLite) GetUserProfileImgURL() string {
	if x != nil {
		return x.UserProfileImgURL
	}
	return ""
}

var File_pkg_infrastructure_pb_auth_client_proto protoreflect.FileDescriptor

var file_pkg_infrastructure_pb_auth_client_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x54,
	0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x20,
	0x0a, 0x0b, 0x45, 0x78, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x45, 0x78, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x22, 0x0a, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x87, 0x01, 0x0a, 0x17, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4c, 0x69, 0x74, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x2c, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49,
	0x6d, 0x67, 0x55, 0x52, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6d, 0x67, 0x55, 0x52, 0x4c, 0x32, 0xb5,
	0x01, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5f,
	0x0a, 0x1d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x4c, 0x69, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x56, 0x69, 0x65, 0x77, 0x12,
	0x19, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x23, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4c, 0x69, 0x74, 0x65, 0x12,
	0x45, 0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x12, 0x19, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x18, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x42, 0x19, 0x5a, 0x17, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_infrastructure_pb_auth_client_proto_rawDescOnce sync.Once
	file_pkg_infrastructure_pb_auth_client_proto_rawDescData = file_pkg_infrastructure_pb_auth_client_proto_rawDesc
)

func file_pkg_infrastructure_pb_auth_client_proto_rawDescGZIP() []byte {
	file_pkg_infrastructure_pb_auth_client_proto_rawDescOnce.Do(func() {
		file_pkg_infrastructure_pb_auth_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_infrastructure_pb_auth_client_proto_rawDescData)
	})
	return file_pkg_infrastructure_pb_auth_client_proto_rawDescData
}

var file_pkg_infrastructure_pb_auth_client_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_infrastructure_pb_auth_client_proto_goTypes = []interface{}{
	(*RequestUserId)(nil),           // 0: auth_proto.RequestUserId
	(*ResponseBool)(nil),            // 1: auth_proto.ResponseBool
	(*ResponseUserDetailsLite)(nil), // 2: auth_proto.ResponseUserDetailsLite
}
var file_pkg_infrastructure_pb_auth_client_proto_depIdxs = []int32{
	0, // 0: auth_proto.AuthService.GetUserDetailsLiteForPostView:input_type -> auth_proto.RequestUserId
	0, // 1: auth_proto.AuthService.CheckUserExist:input_type -> auth_proto.RequestUserId
	2, // 2: auth_proto.AuthService.GetUserDetailsLiteForPostView:output_type -> auth_proto.ResponseUserDetailsLite
	1, // 3: auth_proto.AuthService.CheckUserExist:output_type -> auth_proto.ResponseBool
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_infrastructure_pb_auth_client_proto_init() }
func file_pkg_infrastructure_pb_auth_client_proto_init() {
	if File_pkg_infrastructure_pb_auth_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_infrastructure_pb_auth_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestUserId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_infrastructure_pb_auth_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseBool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_infrastructure_pb_auth_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseUserDetailsLite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_infrastructure_pb_auth_client_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_infrastructure_pb_auth_client_proto_goTypes,
		DependencyIndexes: file_pkg_infrastructure_pb_auth_client_proto_depIdxs,
		MessageInfos:      file_pkg_infrastructure_pb_auth_client_proto_msgTypes,
	}.Build()
	File_pkg_infrastructure_pb_auth_client_proto = out.File
	file_pkg_infrastructure_pb_auth_client_proto_rawDesc = nil
	file_pkg_infrastructure_pb_auth_client_proto_goTypes = nil
	file_pkg_infrastructure_pb_auth_client_proto_depIdxs = nil
}
